version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/authn-service"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "Sunil0916"
    reviewers:
      - "git-madhu"
    commit-message:
      prefix: "pip"
